# This workflow deploys your Firebase Hosting site on every push to main
# Works for multi-page web apps

name: Deploy to Firebase Hosting

# Trigger workflow on push to main
on:
  push:
    branches:
      - main

permissions:
  contents: read  # allows workflow to read repo contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STUDIO_7578418568_F8D83 }}
          projectId: studio-7578418568-f8d83
